apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: investment-analysis-frontend
          image: ssbfc2001/investment_analysis_frontend:v2
          ports:
          - containerPort: 8501 # streamlit
          env:
            - name: STREAMLIT_URL
              value: http://127.0.0.1:8501
            # may need work out backend/postgres env
