apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    role: backend
spec:
  containers:
    - name: investment-analysis-backend
      image: ssbfc2001/investment-analysis-backend:v6
      ports:
        - name: backend
          containerPort: 5000