from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field

class TracePayload(BaseModel):
    model_config = {"extra": "forbid"}

    trace_id: str = Field(..., description="Unique UUID identifying the global transaction chain")
    service_name: str = Field(..., description="Source microservice name reporting telemetry")
    workflow_path: List[str] = Field(..., description="Ordered breadcrumbs of service execution nodes")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="UTC trace generation time")
    prompt_token_count: int = Field(..., ge=0, description="Total tokens consumed in input context windows")
    completion_token_count: int = Field(..., ge=0, description="Total tokens generated by the core model layer")
    tool_invocation_latency: Dict[str, float] = Field(..., description="Key-value mapping of specific tools to execution times in milliseconds")
    runtime_errors: Optional[List[str]] = Field(None, description="Collected stack traces or explicit failure messages")
