name: 'economic_industry_dashboard'
version: '1.0.0'
config-version: 2

profile: 'redshift'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
